#!/bin/bash
echo "turn off IPV6"
read a
if [[ $a = y ]]
  then
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
fi
  if [[ $a = n ]]
  then
echo "turn IPV6 back on?"
read b
  fi
if [[ $b = y ]]
then
  sudo  sysctl -w net.ipv6.conf.all.disable_ipv6=0
  sudo  sysctl -w net.ipv6.conf.default.disable_ipv6=0
fi
