#!/bin/bash
sudo systemctl start windscribe
windscribe connect
echo 'done with session'
read a
if [[ $a == "y" ]]
then
  windscribe disconnect
  systemctl restart NetworkManager.service
else
  echo 'exited'
fi
